<?php if(!isset($conn)){ include 'db_connect.php';
include 'session.php'; }
include 'header.php';
include 'topbar.php';
// echo $_SESSION['login_id'];
// // echo $i;
// echo $_SESSION['name'];
// $pr= $_GET['pr'];

?>
<style>
  textarea{
    resize: none;
  }
</style>
<?php
  $sql="SELECT * FROM parcels WHERE id =(SELECT MAX(id) FROM parcels)";
  $result = $conn->query($sql);
  if($result->num_rows > 0){
    while($row = $result->fetch_assoc()){
    $pr=  $row['price'];
    
    }}
?>
        <?php
$apiKey="rzp_test_uiSQbXtkbUJ4gE";
?>


<script src="https://code.jquery.com/jquery-3.5.0.js"></script>

<form action="" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $pr * 100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="order_CgmcjRh9ti2lP7"// Replace with the order_id generated by you in the backend.
    data-buttontext="Proceed to pay"
    data-name="Fragrance IND"
    data-description="Moovit."
    data-image="https://st4.depositphotos.com/31445094/41249/v/1600/depositphotos_412499652-stock-illustration-perfume-icon-design-template-isolated.jpg"
    data-prefill.name="Minu Joe"
    data-prefill.email=""
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden" class="btn btn-primary">
</form>
<!--gateway end-->

<style>
    .razorpay-payment-button{
        background-color: #0DCAF0;
        color: white;
        font-size: 18px;padding: 8px 10px;font-weight: bold;
        border-radius: 12px; border: none;text-align: center; 
    }
</style>

  